spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # La URL ya lleva el puerto 6543 de la variable DB_URL
    url: jdbc:postgresql://${DB_URL}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true

server:
  port: 8080