spring:
  application:
    name: Conflict_Tracker_api_Tadeuos-San-Baudelio_y_Justin-Alvarez

  profiles:
    active: prod

  datasource:
    # Eliminamos cualquier valor por defecto. Si no hay variable, la app debe fallar con "URL not found"
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # Esto fuerza a Hibernate a no intentar adivinar nada y usar Postgres directamente
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}