spring:
  application:
    name: Conflict_Tracker_api_Tadeuos-San-Baudelio_y_Justin-Alvarez

  # Mantenemos el perfil dev por defecto para cuando trabajes en local
  profiles:
    active: dev

  datasource:
    # Intenta leer la variable de la nube, si no existe, usa localhost
    url: ${DB_URL:jdbc:postgresql://localhost:5432/conflict_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 'update' es vital para que Spring cree las tablas en Supabase por ti
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuración para que Railway/Render asigne el puerto automáticamente
  main:
    allow-bean-definition-overriding: true
server:
  port: ${PORT:8080}